## Cassandra

In [3]:
Why cassandra (NoSQL)

1) Scalability --> we can increase our space or memory capacity
2) High availabilty -->
3) decentralise --> no single failurer
4) scalable -->

SyntaxError: invalid syntax (1014675625.py, line 1)

In [2]:
SQL is known as Vertically Scalabel system whereas 
Cassandra is known as Horizontally scalabel system

SyntaxError: invalid syntax (4099722503.py, line 1)

In [4]:
! pip install cassandra-driver

^C

In [6]:
pip install cassandra-driver

Requirement already satisfied: cassandra-driver in c:\users\win11\anaconda3\lib\site-packages (3.25.0)
Requirement already satisfied: geomet<0.3,>=0.1 in c:\users\win11\anaconda3\lib\site-packages (from cassandra-driver) (0.2.1.post1)
Requirement already satisfied: six>=1.9 in c:\users\win11\anaconda3\lib\site-packages (from cassandra-driver) (1.16.0)
Requirement already satisfied: click in c:\users\win11\anaconda3\lib\site-packages (from geomet<0.3,>=0.1->cassandra-driver) (8.0.4)
Requirement already satisfied: colorama in c:\users\win11\anaconda3\lib\site-packages (from click->geomet<0.3,>=0.1->cassandra-driver) (0.4.4)
Note: you may need to restart the kernel to use updated packages.

# Introduction To Pandas

In [6]:
import pandas as pd

In [11]:
pd.read_csv(r"C:\Users\win11\Downloads\ohana-api-master\data\sample-csv\locations.csv").head()

,id,organization_id,accessibility,admin_emails,alternate_name,description,email,languages,latitude,longitude,name,short_desc,transportation,website,virtual
0,1,1,"disabled_parking, ramp, restroom, wheelchair",NaN,NaN,A walk-in center for older adults that provide...,NaN,"Spanish, Tagalog",37.477227,-122.213221,Fair Oaks Adult Activity Center,A multipurpose senior citizens' center serving...,SAMTRANS stops in front.,NaN,False
1,2,1,wheelchair,NaN,NaN,Provides training and job placement to eligibl...,NaN,"Chinese (Mandarin), Tagalog, Italian, Spanish",37.563984,-122.325799,Second Career Employment Program,Provides training and job placement to eligibl...,"SAMTRANS stops within 1 block, CALTRAIN stops ...",NaN,False
2,3,1,NaN,NaN,NaN,Offers supportive counseling services to San M...,NaN,"Chinese (Cantonese), Chinese (Mandarin), Tagal...",37.563984,-122.325799,Senior Peer Counseling,Offers supportive counseling services to older...,Service is provided in person's home or at a m...,NaN,False
3,4,1,wheelchair,NaN,NaN,Provides supervised visitation services and a ...,NaN,Spanish,37.563984,-122.325799,Family Visitation Center,Provides supervised visitation services and a ...,"SAMTRANS stops within 1 block, CALTRAIN stops ...",NaN,False
4,5,1,wheelchair,NaN,NaN,Provides fixed 8% short term loans to eligible...,NaN,"Hindi, Spanish",37.563984,-122.325799,Economic Self - Sufficiency Program,Makes small loans to working families.,SAMTRANS stops within 1 block. CALTRAIN stops ...,NaN,False

In [15]:
pd.read_csv(r"C:\Users\win11\Downloads\ohana-api-master\data\sample-csv\taxonomy.csv")

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]